export const TOOL_CATEGORIES = {
  text: { label: 'Texto', color: 'text-gold' },
  image: { label: 'Imagem', color: 'text-gold' },
  audio: { label: 'Áudio', color: 'text-gold' },
  code: { label: 'Código', color: 'text-gold' },
};

export const TOOLS = [
  {
    id: 'chat',
    name: 'ALPS Chat',
    description: 'Converse com IA avançada para qualquer pergunta',
    category: 'text',
    credits: 1,
    icon: 'MessageSquare',
    available: true,
    route: '/chat',
  },
  {
    id: 'writer',
    name: 'Redator IA',
    description: 'Crie textos, artigos e copys profissionais',
    category: 'text',
    credits: 2,
    icon: 'PenLine',
    available: true,
    route: '/chat?mode=writer',
  },
  {
    id: 'translator',
    name: 'Tradutor',
    description: 'Traduza textos em dezenas de idiomas',
    category: 'text',
    credits: 1,
    icon: 'Languages',
    available: true,
    route: '/chat?mode=translator',
  },
  {
    id: 'image-gen',
    name: 'Gerador de Imagens',
    description: 'Crie imagens impressionantes com IA',
    category: 'image',
    credits: 10,
    icon: 'ImageIcon',
    available: true,
    route: '/image',
  },
  {
    id: 'image-edit',
    name: 'Editor Visual',
    description: 'Edite e transforme imagens com IA',
    category: 'image',
    credits: 15,
    icon: 'Wand2',
    available: false,
    route: '/image',
  },
  {
    id: 'voice-gen',
    name: 'Narração IA',
    description: 'Converta texto em voz natural',
    category: 'audio',
    credits: 5,
    icon: 'Mic',
    available: false,
    route: '#',
  },
  {
    id: 'transcribe',
    name: 'Transcrição',
    description: 'Transcreva áudios para texto',
    category: 'audio',
    credits: 3,
    icon: 'AudioLines',
    available: false,
    route: '#',
  },
  {
    id: 'code-assist',
    name: 'Assistente de Código',
    description: 'Gere e revise código em qualquer linguagem',
    category: 'code',
    credits: 2,
    icon: 'Code2',
    available: true,
    route: '/chat?mode=code',
  },
  {
    id: 'code-explain',
    name: 'Explicador de Código',
    description: 'Entenda qualquer trecho de código',
    category: 'code',
    credits: 1,
    icon: 'FileCode',
    available: true,
    route: '/chat?mode=explain',
  },
];

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    credits: 100,
    period: 'mês',
    features: [
      '100 créditos por mês',
      'Acesso a ferramentas básicas',
      'Chat com IA',
      'Histórico limitado (7 dias)',
    ],
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 9.90,
    credits: 2000,
    period: 'mês',
    features: [
      '2.000 créditos por mês',
      'Todas as ferramentas',
      'Geração de imagens premium',
      'Histórico completo',
      'Suporte prioritário',
    ],
    highlighted: true,
  },
  {
    id: 'unlimited',
    name: 'Unlimited',
    price: 99.90,
    credits: 999999,
    period: 'mês',
    features: [
      'Créditos ilimitados',
      'Todas as ferramentas premium',
      'Modelos de IA avançados',
      'Histórico permanente',
      'Suporte dedicado 24/7',
      'Acesso antecipado a novidades',
    ],
    highlighted: false,
  },
];